{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "12b2179f-db4a-4c3f-991c-dc65e45fd2f9",
   "metadata": {},
   "outputs": [],
   "source": [
    "!pip install jieba\n",
    "!pip install pathlib\n",
    "!pip install nltk wordcloud matplotlib pandas\n",
    "!pip install wordcloud\n",
    "import re\n",
    "from collections import Counter\n",
    "from pathlib import Path\n",
    "import matplotlib.pyplot as plt\n",
    "import nltk\n",
    "import pandas as pd\n",
    "from wordcloud import STOPWORDS as WORDCLOUD_STOPWORDS\n",
    "from wordcloud import WordCloud\n",
    "import jieba\n",
    "import streamlit as st\n",
    "import contextlib, io\n",
    "\n",
    "resources = {\n",
    "    \"punkt\": \"tokenizers/punkt\",\n",
    "    \"punkt_tab\": \"tokenizers/punkt_tab\",\n",
    "    \"stopwords\": \"corpora/stopwords\",\n",
    "    \"wordnet\": \"corpora/wordnet\",\n",
    "    \"omw-1.4\": \"corpora/omw-1.4\",\n",
    "    \"averaged_perceptron_tagger_eng\": \"taggers/averaged_perceptron_tagger_eng\",\n",
    "}\n",
    "\n",
    "for package, lookup_path in resources.items():\n",
    "    try:\n",
    "        nltk.data.find(lookup_path)\n",
    "    except LookupError:\n",
    "        with contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(io.StringIO()):\n",
    "            nltk.download(package, quiet=True, raise_on_error=False)\n",
    "\n",
    "csv_path = 'food.csv'\n",
    "df = pd.read_csv(csv_path)\n",
    "\n",
    "custom_terms = ['水潤餅', '柴梳餅', '竹塹餅', '銀耳蓮子湯', '麻糬紅豆Q餅', '水蒸蛋糕']\n",
    "for term in custom_terms:\n",
    "    jieba.add_word(term)\n",
    "with open(\"chinese_stopwords.txt\", \"r\", encoding=\"utf-8\") as f:\n",
    "    STOPWORDS = f.read().splitlines()\n",
    "\n",
    "df['clean_text'] = df['介紹'].fillna('').astype(str)\n",
    "\n",
    "df['clean_text'] = df['clean_text'].str.replace(r'\\\\n', ' ', regex=True)\n",
    "\n",
    "df['clean_text'] = df['clean_text'].str.replace(r'[^\\u4e00-\\u9fffA-Za-z\\s]', ' ', regex=True)\n",
    "\n",
    "raw_tokens = [jieba.lcut(x) for x in df['clean_text']]\n",
    "df['raw_tokens'] = raw_tokens\n",
    "\n",
    "df['clean_tokens'] = [\n",
    "    [token.strip().lower() for token in token_list]\n",
    "    for token_list in df['raw_tokens']\n",
    "]\n",
    "\n",
    "df['tokens'] = [\n",
    "    [\n",
    "        token\n",
    "        for token in token_list\n",
    "        if token != '' and token not in STOPWORDS\n",
    "    ]\n",
    "    for token_list in df['clean_tokens']\n",
    "]\n",
    "\n",
    "all_tokens = []\n",
    "for tokens in df['tokens']:\n",
    "    for token in tokens:\n",
    "        all_tokens.append(token)\n",
    "        \n",
    "top_terms = pd.DataFrame(Counter(all_tokens).most_common(20), columns=['term', 'count'])\n",
    "\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.font_manager as fm\n",
    "\n",
    "def setup_cjk_font():\n",
    "    candidates = [\n",
    "        'Noto Sans CJK TC',\n",
    "        'Noto Sans CJK SC',\n",
    "        'Noto Sans CJK JP',\n",
    "        'Microsoft JhengHei',\n",
    "        'PingFang TC',\n",
    "        'SimHei',\n",
    "        'Arial Unicode MS'\n",
    "    ]\n",
    "\n",
    "    available_fonts = fm.fontManager.ttflist\n",
    "\n",
    "    for font in candidates:\n",
    "        for f in available_fonts:\n",
    "            if font == f.name:\n",
    "                plt.rcParams['font.family'] = 'sans-serif'\n",
    "                plt.rcParams['font.sans-serif'] = [font]\n",
    "                plt.rcParams['axes.unicode_minus'] = False\n",
    "\n",
    "                print(f'Using font: {font}')\n",
    "                print(f'Font path: {f.fname}')\n",
    "\n",
    "                return f.fname\n",
    "\n",
    "    print('No CJK font found by matplotlib.')\n",
    "    return None\n",
    "\n",
    "font_path = setup_cjk_font()\n",
    "\n",
    "st.title(\"新竹水潤餅文字雲\")\n",
    "\n",
    "num_words = st.slider(\n",
    "    \"選擇文字數量\",\n",
    "    min_value=1,\n",
    "    max_value=1000,\n",
    "    value=100,\n",
    "    step=1\n",
    ")\n",
    "\n",
    "filtered_terms = top_terms.head(num_words)\n",
    "\n",
    "freq_dict = dict(zip(\n",
    "    filtered_terms['term'],\n",
    "    filtered_terms['count']\n",
    "))\n",
    "\n",
    "wc = WordCloud(\n",
    "    font_path=font_path,\n",
    "    width=1000,\n",
    "    height=600,\n",
    "    background_color='white',\n",
    "    collocations=False\n",
    ").generate_from_frequencies(freq_dict)\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(12, 7))\n",
    "\n",
    "ax.imshow(wc)\n",
    "ax.axis('off')\n",
    "st.pyplot(fig)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
